delete from COCO_ROLE_MENU;
delete from COCO_POST_ROLE;
delete from COCO_USER_POST;
delete from COCO_ROLE;
delete from COCO_POST;
delete from COCO_USER;
delete from COCO_PERSON;
delete from COCO_DEPT;

INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1000', '中日达', '1', '0', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1001', '董事长', '1', '1000', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1002', '总经理', '1', '1001', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1003', '副总经理', '', '1002', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1004', '总经理特别助理', '', '1002', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1005', '行政', '', '1003', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1006', '财务', '2', '1003', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1007', '采购', '2', '1003', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1008', '营业部长', '', '1003', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1009', '劳安课', '', '1005', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1010', '总务课', '', '1005', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1011', '人事课', '', '1005', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1012', '保安队', '', '1009', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1013', '医务室', '', '1009', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1014', '厨房组', '', '1010', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1015', '司机组', '', '1010', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1016', '营业经理', '', '1008', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1017', '进出口物流课', '', '1008', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1018', '营业会计课', '', '1008', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1019', '北中国', '', '1016', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1020', '南中国、出口课', '', '1016', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1021', '营业调整课', '', '1016', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1022', '制造部经理', '', '1046', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1023', 'ETL', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1024', 'SL', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1025', '捆包', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1026', '生产管理', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1027', '技术室', '2', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1028', '品质管理', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1029', '动力', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1030', '机械保全', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1031', '电气保全', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1032', '电气技术室', '', '1022', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1033', 'ETL生产线', '', '1023', '', 1, '20');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1034', '铸造室', '', '1023', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1035', '2SL', '', '1024', '', 1, '20');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1036', '3SL', '', '1024', '', 1, '20');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1037', '选别', '', '1024', '', 1, '20');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1038', '片材捆包', '', '1025', '', 1, '20');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1039', '外贩材捆包', '', '1025', '', 1, '20');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1040', '木工所', '', '1025', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1041', '受入', '', '1026', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1042', '出荷', '', '1026', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1043', '分析室', '', '1028', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1044', '生产计划室', '', '1004', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1045', '总经理室', '', '1004', '', 1, '00');
INSERT INTO COCO_DEPT (ID_, NAME_, ORDER_, PARENT_, REMARK_, VALID_, TYPE_) VALUES('1046', '副总经理(厂长)', '', '1002', '', 1, '00');

insert into COCO_PERSON (ID_, NAME_, NO_, DEPT_, VALID_, ORDER_) values('1000', '管理员', '000', '1026', 1, '1');
insert into COCO_PERSON (ID_, NAME_, NO_, DEPT_, VALID_, ORDER_) values('1999', '许德建', '999', '1026', 1, '1');
insert into COCO_PERSON (ID_, NAME_, NO_, DEPT_, VALID_, ORDER_) values('1998', 'ETL', '998', '1033', 1, '1');
insert into COCO_PERSON (ID_, NAME_, NO_, DEPT_, VALID_, ORDER_) values('1997', 'SL2', '997', '1035', 1, '1');
insert into COCO_PERSON (ID_, NAME_, NO_, DEPT_, VALID_, ORDER_) values('1996', 'SL3', '996', '1036', 1, '1');
insert into COCO_PERSON (ID_, NAME_, NO_, DEPT_, VALID_, ORDER_) values('1995', 'XB', '995', '1037', 1, '1');
insert into COCO_PERSON (ID_, NAME_, NO_, DEPT_, VALID_, ORDER_) values('1994', 'SS', '994', '1038', 1, '1');
insert into COCO_PERSON (ID_, NAME_, NO_, DEPT_, VALID_, ORDER_) values('1993', 'FXS', '993', '1043', 1, '1');

insert into COCO_USER (ID_, GRADE_, PSWD_, PERSON_, VALID_, ORDER_) values('admin', '1', 'Tq9o/tZpZFM=', '1000', 1, '1');
insert into COCO_USER (ID_, GRADE_, PSWD_, PERSON_, VALID_, ORDER_) values('xdj', '1', 'Tq9o/tZpZFM=', '1999', 1, '1');
insert into COCO_USER (ID_, GRADE_, PSWD_, PERSON_, VALID_, ORDER_) values('etl', '1', 'Tq9o/tZpZFM=', '1998', 1, '1');
insert into COCO_USER (ID_, GRADE_, PSWD_, PERSON_, VALID_, ORDER_) values('sl2', '1', 'Tq9o/tZpZFM=', '1997', 1, '1');
insert into COCO_USER (ID_, GRADE_, PSWD_, PERSON_, VALID_, ORDER_) values('sl3', '1', 'Tq9o/tZpZFM=', '1996', 1, '1');
insert into COCO_USER (ID_, GRADE_, PSWD_, PERSON_, VALID_, ORDER_) values('xb', '1', 'Tq9o/tZpZFM=', '1995', 1, '1');
insert into COCO_USER (ID_, GRADE_, PSWD_, PERSON_, VALID_, ORDER_) values('ss', '1', 'Tq9o/tZpZFM=', '1994', 1, '1');
insert into COCO_USER (ID_, GRADE_, PSWD_, PERSON_, VALID_, ORDER_) values('fxs', '1', 'Tq9o/tZpZFM=', '1993', 1, '1');

insert into COCO_POST (ID_, NAME_, DEPT_, PRIV_DEPT_, VALID_, SHARE_, CONTAIN_) values('1000', '系统管理', '1000', '1000', 1, 1, 0);
insert into COCO_POST (ID_, NAME_, DEPT_, PRIV_DEPT_, VALID_, SHARE_, CONTAIN_) values('1001', '业务管理', '1026', '1026', 1, 1, 1);
insert into COCO_POST (ID_, NAME_, DEPT_, PRIV_DEPT_, VALID_, SHARE_, CONTAIN_) values('etl', '业务管理', '1033', '1033', 1, 1, 1);
insert into COCO_POST (ID_, NAME_, DEPT_, PRIV_DEPT_, VALID_, SHARE_, CONTAIN_) values('sl2', '业务管理', '1035', '1035', 1, 1, 1);
insert into COCO_POST (ID_, NAME_, DEPT_, PRIV_DEPT_, VALID_, SHARE_, CONTAIN_) values('sl3', '业务管理', '1036', '1036', 1, 1, 1);
insert into COCO_POST (ID_, NAME_, DEPT_, PRIV_DEPT_, VALID_, SHARE_, CONTAIN_) values('xb', '业务管理', '1037', '1037', 1, 1, 1);
insert into COCO_POST (ID_, NAME_, DEPT_, PRIV_DEPT_, VALID_, SHARE_, CONTAIN_) values('ss', '业务管理', '1038', '1038', 1, 1, 1);
insert into COCO_POST (ID_, NAME_, DEPT_, PRIV_DEPT_, VALID_, SHARE_, CONTAIN_) values('fxs', '业务管理', '1043', '1043', 1, 1, 1);

insert into COCO_USER_POST(USER_, POST_) values('admin', '1000');
insert into COCO_USER_POST(USER_, POST_) values('xdj', '1001');
insert into COCO_USER_POST(USER_, POST_) values('etl', 'etl');
insert into COCO_USER_POST(USER_, POST_) values('sl2', 'sl2');
insert into COCO_USER_POST(USER_, POST_) values('sl3', 'sl3');
insert into COCO_USER_POST(USER_, POST_) values('xb', 'xb');
insert into COCO_USER_POST(USER_, POST_) values('ss', 'ss');
insert into COCO_USER_POST(USER_, POST_) values('fxs', 'fxs');

insert into COCO_ROLE (ID_, NAME_, VALID_, DESCRIPTION_) values('1000', '超级管理员', 1, '');
insert into COCO_ROLE (ID_, NAME_, VALID_, DESCRIPTION_) values('1001', '管理员', 1, '');
insert into COCO_ROLE (ID_, NAME_, VALID_, DESCRIPTION_) values('etl', 'ETL操作员', 1, '');
insert into COCO_ROLE (ID_, NAME_, VALID_, DESCRIPTION_) values('sl', 'SL操作员', 1, '');
insert into COCO_ROLE (ID_, NAME_, VALID_, DESCRIPTION_) values('xb', '选别操作员', 1, '');
insert into COCO_ROLE (ID_, NAME_, VALID_, DESCRIPTION_) values('ss', '捆包操作员', 1, '');
insert into COCO_ROLE (ID_, NAME_, VALID_, DESCRIPTION_) values('fxs', '分析室操作员', 1, '');

insert into COCO_POST_ROLE (POST_, ROLE_) values('etl', 'etl');
insert into COCO_POST_ROLE (POST_, ROLE_) values('sl2', 'sl');
insert into COCO_POST_ROLE (POST_, ROLE_) values('sl3', 'sl');
insert into COCO_POST_ROLE (POST_, ROLE_) values('xb', 'xb');
insert into COCO_POST_ROLE (POST_, ROLE_) values('ss', 'ss');
insert into COCO_POST_ROLE (POST_, ROLE_) values('fxs', 'fxs');

insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '1');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '40');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4001');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4002');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4003');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4004');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4005');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4006');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4007');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4008');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4009');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4010');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4011');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4012');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4013');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4014');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4015');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4016');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('etl', '4017');

insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '1');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '50');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5001');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5002');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5003');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5004');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5005');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5006');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5007');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5008');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5009');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5010');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('sl', '5011');

insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '1');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '60');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '6001');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '6002');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '6003');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '6004');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '6005');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '6006');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '6007');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('xb', '6008');

insert into COCO_ROLE_MENU (ROLE_, MENU_) values('ss', '1');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('ss', '70');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('ss', '7001');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('ss', '7002');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('ss', '7003');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('ss', '7004');

insert into COCO_ROLE_MENU (ROLE_, MENU_) values('fxs', '1');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('fxs', '72');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('fxs', '7201');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('fxs', '7202');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('fxs', '7203');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('fxs', '7204');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('fxs', '7205');
insert into COCO_ROLE_MENU (ROLE_, MENU_) values('fxs', '7206');