--初始化码表
delete from COCO_CODE_ITEM;
delete from COCO_CODE;

insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('COCO_DEPT_TYPE','部门类型',1,1);

insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('NWX','内外销',1,1);
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SHD','',1,1);

insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_DC','货柜海运和出口，堆场费用',1,1);
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_CK_CY','出口运输方式，船运',1,1);
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_TLYS','铁路运输，中日达到终点站和终点站到客户 ',1,1);
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_HGHY_MDG','货柜海运，目的港到客户',1,1);
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_KHYF_DW','运费单位',1,1);

insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('SINO_HGHY_CY', '货柜海运，船运', 0, 1);
insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('SINO_DQSG', '货柜海运、公路运输和出口，中日达到起始港', 0, 1);
insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('SINO_SHHY', '散货海运，中日达到目的港和目的港到客户', 0, 1);
insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('SINO_CK_MDG', '出口运输方式，目的港到客户', 0, 1);


insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('QYWL', '采购合同签约完了标志', 0, 1);

insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('SPBH', '根据现品厚度获得商品编号', 0, 1);
insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('ZSFP', '指示书分派', 0, 1);
insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('ZSJJ', '指示书紧急程度', 0, 1);

insert into COCO_CODE (ID_, DESCRIPTION_, EDITABLE_, VALID_) values ('DUIC', '堆场', 0, 1);

insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_BAN',1,1, '生产班别');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_ZU',1,1, '生产组别');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_CYFX_XM',1,1, '采样分析项目');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_CYFX_WZ',1,1, '采样分析位置');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('XPZK',1,1, '现品状况');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('TZJE',1,1, '调整金额');

insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_ZK_PASS',1,1, 'PASS');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_FXS_BW',1,1, '部位');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_FXS_LX',1,1, '类型');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_ZK_TYJMS',1,1, '涂油机目视');

insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('MYHL',1,1, '美元汇率');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('BFHL',1,1, '保费汇率');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('GSSL',1,1, '关税税率');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('YBYSGS',1,1, '原板运输公司码头到中日达。运输税率（每吨的价格）');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('XCMT',1,1, '卸船码头。港杂税率（每吨的价格）');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_YSFS',1,1, '运输方式');

insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_DH_STAT',1,1, '订货合同状态');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('ZpSTAT',1,1, '制品状态');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_YB_STAT',1,1, '原板状态');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_CH_STAT',1,1, '装箱指示书出货状态');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_CHLLD_STAT',1,1, '出货联络单状态');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_JBDD_STAT',1,1, '基板订购单状态');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_FKFP_STAT',1,1, '付款发票状态');

insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_CAOZ',1,1, '指示操作类型');

insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_TS_STAT',1,1, '制品投诉状态');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_YBRK',1,1, '原板入库盘点机文件路径');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_CPRK',1,1, '制品入库盘点机文件路径');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_YBDR_GG',1,1, '原板导入规格');
insert into COCO_CODE(ID_,EDITABLE_,VALID_,DESCRIPTION_ ) values('SINO_HJIN',1,1, '合金层');
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_QX','缺陷代码',1,1);
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_BMLJG','表面六价铬',1,1);
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_YCXM','异常项',1,1);
insert into COCO_CODE(ID_,DESCRIPTION_,EDITABLE_,VALID_) values('SINO_MKTFX_STAT','马口铁分析结果',1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('COCO_DEPT_TYPE','00','保留','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('COCO_DEPT_TYPE','10','机关','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('COCO_DEPT_TYPE','20','生产','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('COCO_DEPT_TYPE','21','生产辅助','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('NWX','1','国内','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('NWX','2','直接出口','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('NWX','3','直接出口','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','1','厦门','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','2','漳州','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','3','集美','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','4','新港','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','5','码头','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','6','德通','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','7','升兴','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','8','东站','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','9','长途','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SHD','10','自提','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_KHYF_DW','1','RMB/吨','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_KHYF_DW','2','RMB/柜','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_KHYF_DW','3','USB/柜','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_DC','1','天择堆场','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_CK_CY','1','福州外代','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_TLYS','1','福建鸿达货运公司','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_TLYS','2','福州东铁运输服务有限公司','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_TLYS','3','福州畅港公司','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_HGHY_MDG','1','中迅货运','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_HGHY_MDG','2','上海杨思交通运输管理站','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_HGHY_MDG','3','天津联运运输公司','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_HGHY_CY','1','中迅货运','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_DQSG','1','福州畅港公司','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_DQSG','2','福州鼓楼交通服务货运分公司','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_SHHY','3','港联交易所','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('QYWL','0','未完了','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('QYWL','1','已完了','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SPBH','1','0.15-0.3','0.15<=厚<0.3',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SPBH','2','0.3-0.6','0.3<=厚<0.6',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SPBH','3','0.6-1','0.6<=厚<1',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('ZSFP','0','未分派','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('ZSFP','1','已分派','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('ZSJJ','0','否','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('ZSJJ','1','是','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('DUIC','X','X堆场','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('DUIC','A','A堆场','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('DUIC','B','B堆场','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('DUIC','C','C堆场','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('DUIC','D','D堆场','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('DUIC','E','E堆场','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('DUIC','F','F堆场','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('DUIC','G','G堆场','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_BAN','1','一班','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_BAN','2','二班','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_BAN','3','三班','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_ZU','A','A组','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_ZU','B','B组','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_ZU','C','C组','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_ZU','D','D组','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','涂油量','涂油量','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','锡附着量','锡附着量','',1,1,1,'2');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','Cr','Cr','',1,1,1,'3');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','表面六价铬','表面六价铬','',1,1,1,'4');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','ATC','ATC','',1,1,1,'5');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','TCV','TCV','',1,1,1,'6');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','ISV','ISV','',1,1,1,'7');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','TCS评点','TCS评点','',1,1,1,'8');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','污点试验','污点试验','',1,1,1,'9');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','Epon Flow','Epon Flow','',1,1,1,'10');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','PLT sec','PLT sec','',1,1,1,'11');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','PORE','PORE','',1,1,1,'12');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_XM','涂料密着性','涂料密着性','',1,1,1,'13');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FXS_BW','T','头部','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FXS_BW','M','中部','',1,1,1,'2');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FXS_BW','B','尾部','',1,1,1,'3');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FXS_LX','A','A','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FXS_LX','B','B','',1,1,1,'2');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FXS_LX','C','C','',1,1,1,'3');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FXS_LX','D','D','',1,1,1,'4');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_ZK_PASS','1','使用','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_ZK_PASS','2','不使用','',1,1,1,'2');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_ZK_TYJMS','0','NG','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_ZK_TYJMS','1','OK','',1,1,1,'2');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_WZ','T','T','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_WZ','M','M','',1,1,1,'2');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CYFX_WZ','B','B','',1,1,1,'3');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('XPZK','A','素材','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('XPZK','B','中间品','',1,1,1,'2');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('XPZK','C','卷材制品','',1,1,1,'3');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('XPZK','D','板材制品','',1,1,1,'3');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('TZJE','1','0.01','调整金额范围最小值',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('TZJE','2','10','调整金额范围最大值',1,1,1,'2');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('MYHL','1','0.01','美元汇率',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('BFHL','1','0.01','保费汇率',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('GSSL','1','0.01','关税税率',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('YBYSGS','1','运输公司1','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('YBYSGS','2','运输公司2','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('XCMT','1','码头1','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('XCMT','2','码头2','',1,1,1,'1');


insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YSFS','1','货柜海运','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YSFS','2','散货海运','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YSFS','3','公路运输','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YSFS','4','铁路运输','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YSFS','5','出口','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YSFS','6','自提','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_DH_STAT','0','初始','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_DH_STAT','1','上锁','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_DH_STAT','2','仕样确认','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_DH_STAT','3','已分配','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_DH_STAT','4','已完成','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('ZpSTAT','0','初始','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('ZpSTAT','1','实绩录入','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('ZpSTAT','2','实绩终了','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('ZpSTAT','3','实绩中止','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YB_STAT','0','初始','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YB_STAT','1','已入库','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YB_STAT','2','已分配','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YB_STAT','3','实绩录入','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YB_STAT','4','实绩终了','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YB_STAT','5','实绩终止','',1,1,1,'1');


insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CH_STAT','0','初始','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CH_STAT','1','已发货','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CH_STAT','2','作废','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CAOZ','S','板材','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CAOZ','C','卷材','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CHLLD_STAT','0','未锁','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CHLLD_STAT','1','已锁','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CHLLD_STAT','2','已打单','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_CHLLD_STAT','3','已结束','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_JBDD_STAT','0','初始','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_JBDD_STAT','1','已制作','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_JBDD_STAT','2','作废','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FKFP_STAT','0','初始','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FKFP_STAT','1','冲帐未结束','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_FKFP_STAT','2','冲帐已结束','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_TS_STAT','0','初始','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_TS_STAT','1','投诉','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_TS_STAT','2','退货','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_TS_STAT','3','厂外转卖','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_TS_STAT','4','撤销投诉','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_YBDR_GG','','','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_HJIN','5','5','',1,1,1,'1');
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_, ORDER_) values('SINO_HJIN','0.5','0.5','',1,1,1,'1');

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A0','A0','挤干不良',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A1','A1','未电镀',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A2','A2','未电镀刮伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A3','A3','停线痕迹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A4','A4','点斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A5','A5','木纹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A6','A6','低电流',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A7','A7','高电流',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A8','A8','锡盛',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','A9','A9','白点',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B0','B0','Roll印迹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B1','B1','附着量偏差',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B2','B2','锡阳极条纹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B3','B3','Drug Out 污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B4','B4','淬火污斑（高目）',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B5','B5','淬火污斑（低目）',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B6','B6','淬火污斑（洗衣板状）',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B7','B7','化学污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B8','B8','研磨污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','B9','B9','未软熔',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C0','C0','ETL虫子',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C1','C1','白色条痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C2','C2','生油 机油附着',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C3','C3','差厚标记不良',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C4','C4','电弧斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C5','C5','ETL压伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C6','C6','其他污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C7','C7','ETL性异物',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C8','C8','ETL性折痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','C9','C9','筋斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D0','D0','滴下污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D1','D1','辊轮污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D2','D2','ETL性擦伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D3','D3','飞溅污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D4','D4','绞痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D5','D5','干燥机污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D6','D6','刮伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D7','D7','Roll擦痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D8','D8','蚯蚓状污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','D9','D9','厚锡边（白边或亮边）',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E0','E0','单边翘曲',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E1','E1','SL性擦伤.刮伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E2','E2','平整机压痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E3','E3','剪断长不良',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E4','E4','直角度不良',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E5','E5','张数不足（格外）',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E6','E6','张数不足（发生）',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E7','E7','毛边',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E8','E8','L弯曲',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','E9','E9','SL性折痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F0','F0','刀缺口',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F1','F1','SL性压痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F2','F2','卷取不整齐',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F3','F3','内径不良',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F4','F4','重量不足',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F5','F5','摩擦黑斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F6','F6','天车吊钩撞伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F7','F7','Reel痕迹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F8','F8','不整齐',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','F9','F9','零头数',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G0','G0','ENDSTOPPER撞伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G1','G1','二枚板（夹心板）',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G2','G2','爆皮',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G3','G3','条状轧痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G4','G4','线状氧化物',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G5','G5','嵌入氧化物',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G6','G6','板厚不良',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G7','G7','SL虫子',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G8','G8','板宽不良',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','G9','G9','SL性异物',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H0','H0','SL性油斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H1','H1','中伸',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H2','H2','耳波',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H3','H3','耳荒',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H4','H4','白化',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H5','H5','C弯曲',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H6','H6','皱纹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H7','H7','拉伸痕迹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H8','H8','单边耳波',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','H9','H9','RollMark总称',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J0','J0','交叉纹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J1','J1','尖锐Roll性伤痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J2','J2','凸状Roll性伤痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J3','J3','凹状Roll性伤痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J4','J4','DULL秃斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J5','J5','Bar秃斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J6','J6','凹入Roll性伤痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J7','J7','杂Roll性伤痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J8','J8','线状Roll伤痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','J9','J9','卷取翘边',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K1','K1','送给痕迹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K2','K2','震动痕迹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K3','K3','绞纹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K4','K4','接触痕迹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K5','K5','辊轮性刮伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K6','K6','拉伸纹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K7','K7','中部粘结条痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K8','K8','边缘粘结条痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','K9','K9','耳皱 边缘折皱',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L0','L0','油斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L1','L1','原板擦伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L2','L2','原板刮伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L3','L3','刮伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L4','L4','热刮伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L5','L5','凿伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L6','L6','锈',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L7','L7','点锈',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L8','L8','白锈',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','L9','L9','光泽不良',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M0','M0','熔接头痕迹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M1','M1','光泽不均',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M2','M2','原板性油斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M3','M3','油点',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M4','M4','退火暗边',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M5','M5','油污',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M6','M6','粒状污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M7','M7','原板污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M8','M8','剥落',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','M9','M9','硬度异常',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','N2','N2','痘痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','N3','N3','绞痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','N4','N4','订单材结束',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','N5','N5','折痕（总称）',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','N6','N6','灰尘',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','N7','N7','原板刮伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','N8','N8','原板撞伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','P2','P2','平整机白边',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','P3','P3','SL性角撞伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','P4','P4','叉车撞伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','P5','P5','捆包性伤痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','P6','P6','其他ETL性缺陷',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','P7','P7','其他SL性缺陷',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','P8','P8','其他选别性缺陷',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','P9','P9','其他原板性缺陷',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q0','Q0','油斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q1','Q1','电镀污斑',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q2','Q2','压痕',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q3','Q3','Q/S擦伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q4','Q4','交叉纹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q5','Q5','小白亮点',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q6','Q6','笋状',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q7','Q7','内径凹陷',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q8','Q8','太阳纹',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_QX','Q9','Q9','绞伤',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_BMLJG','阴','阴','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_BMLJG','阳','阳','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_YCXM','01','异常项目1','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_YCXM','02','异常项目2','',1,1,1);

insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_MKTFX_STAT','0','未检验','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_MKTFX_STAT','1','合格','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_MKTFX_STAT','2','不合格','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_YBRK','1','d:\\ybrk.txt','',1,1,1);
insert into COCO_CODE_ITEM( CODE_,KEY_,VALUE_,REMARK_,EDITABLE_,DELETABLE_,VALID_) values('SINO_CPRK','1','C:\\原板入库(right).txt','',1,1,1);


